version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django
    environment:
      # please change to your domain.
      DOMAINS: 'housework-app-local.com -> http://django:50000'
      STAGE: 'local'
      CLIENT_MAX_BODY_SIZE: 10M
    # please change to any volumes.
    volumes:
      - /var/lib/ssl_certs/housework-app-local.com:/var/lib/https-portal

  django:
    build: ./django-uwsgi-nginx
    volumes:
      - ./django-uwsgi-nginx/app/static:/usr/share/nginx/html/static
      - ./django-uwsgi-nginx/app/media:/usr/share/nginx/html/media
      - ./logs/django:/var/log/django
      - ./logs/uwsgi:/var/log/uwsgi
      - ./logs/nginx:/var/log/nginx
      - ./django-uwsgi-nginx/app:/code/app
    command: bash -c "cd /code/app && pip3 install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && supervisord -n"
    ports:
      - '50000:50000'