@startuml
'PlantUML(ユースケース図)

:料理担当: as Cook
:買物担当: as Buyer

package 買い物リスト管理 {
left to right direction
Cook -> (5.一定期間分の買い物リストを作成する)
Cook -> (6.買い物リストを確認し、買物担当に依頼する)
}

package 買い物リストチェック{
left to right direction
Buyer -> (7.買い物リストに沿って買い物し、チェックする)
}

package 献立管理 {
left to right direction
Cook --> (4.日付ごとに献立（レシピ群）を登録する)
}

package レシピ管理 {
left to right direction
Cook --> (1.レシピ名・カテゴリ・材料・備考を保存する)
Cook --> (2.レシピへ評価を付与する)
Cook --> (3.レシピを様々な条件で検索する)
}

@enduml